#!/usr/bin/env python3
"""Generate Chromium version stamp files that may be absent in shallow checkouts."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_src(root: Path) -> Path:
    return root / "third_party" / "chromium" / "src"


def run(command: list[str], cwd: Path) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(command)}\n{result.stderr.strip()}"
        )
    return result.stdout.strip()


def ensure_lastchange(src: Path) -> None:
    lastchange = src / "build" / "util" / "lastchange.py"
    run(
        [
            sys.executable,
            str(lastchange),
            "--source-dir",
            ".",
            "--output",
            "build/util/LASTCHANGE",
        ],
        src,
    )

    commit_time = run(["git", "log", "-1", "--format=%ct"], src)
    (src / "build" / "util" / "LASTCHANGE.committime").write_text(
        f"{commit_time}\n", encoding="utf-8"
    )


def ensure_dependency_hash(
    src: Path,
    source_dir: str,
    revision_output: str,
    header_output: str,
    version_macro: str,
) -> None:
    lastchange = src / "build" / "util" / "lastchange.py"
    run(
        [
            sys.executable,
            str(lastchange),
            "-s",
            source_dir,
            "--revision",
            revision_output,
            "--header",
            header_output,
            "--version-macro",
            version_macro,
        ],
        src,
    )


def ensure_gpu_lists_version(src: Path) -> None:
    files = [
        src / "gpu" / "config" / "gpu_driver_bug_list.json",
        src / "gpu" / "config" / "software_rendering_list.json",
    ]
    digest = hashlib.sha256()
    for path in files:
        digest.update(path.name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")

    header = src / "gpu" / "config" / "gpu_lists_version.h"
    version = f"sha256:{digest.hexdigest()[:24]}"
    header.write_text(
        "\n".join(
            [
                "// Generated by DokeBrowser build tooling.",
                "#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_",
                "#define GPU_CONFIG_GPU_LISTS_VERSION_H_",
                "",
                f'#define GPU_LISTS_VERSION "{version}"',
                "",
                "#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_",
                "",
            ]
        ),
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", type=Path, default=default_src(repo_root()))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    src = args.src.resolve()
    if not (src / "build" / "util" / "lastchange.py").exists():
        print(f"chromium_source_missing src={src}", file=sys.stderr)
        return 2

    ensure_lastchange(src)
    ensure_dependency_hash(
        src,
        "third_party/skia",
        "skia/ext/SKIA_VERSION",
        "skia/ext/skia_commit_hash.h",
        "SKIA_COMMIT_HASH",
    )
    ensure_dependency_hash(
        src,
        "third_party/dawn",
        "gpu/webgpu/DAWN_VERSION",
        "gpu/webgpu/dawn_commit_hash.h",
        "DAWN_COMMIT_HASH",
    )
    ensure_gpu_lists_version(src)
    print(f"chromium_generated_versions_ok src={src}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
